package ohos.hdi.distributed_audio.audio.v1_0;

import ohos.hdi.distributed_audio.audio.v1_0.Types;
import ohos.hdi.distributed_audio.audio.v1_0.IAudioRenderCallback;

interface IAudioRender {
    GetLatency([out] unsigned int ms);
    RenderFrame([in] unsigned char[] frame,[in] unsigned long requestBytes,[out] unsigned long replyBytes);
    GetRenderPosition([out] unsigned long frames,[out] struct AudioTimeStampHAL time);
    SetRenderSpeed([in] float speed);
    GetRenderSpeed([out] float speed);
    SetChannelMode([in] enum AudioChannelModeHAL mode);
    GetChannelMode([out] enum AudioChannelModeHAL mode);
    RegCallback([in] IAudioRenderCallback cbObj);
    DrainBuffer([in] enum AudioDrainNotifyTypeHAL type);

    Start();
    Stop();
    Pause();
    Resume();
    Flush();
    TurnStandbyMode();
    AudioDevDump([in] int range,[in] int fd);

    CheckSceneCapability([in] struct AudioSceneDescriptorHAL scene,[out] boolean support);
    SelectScene([in] struct AudioSceneDescriptorHAL scene);

    SetMute([in] boolean mute);
    GetMute([out] boolean mute);
    SetVolume([in] float volume);
    GetVolume([out] float volume);
    GetGainThreshold([out] float min,[out] float max);
    SetGain([in] float gain);
    GetGain([out] float gain);

    GetFrameSize([out] unsigned long size);
    GetFrameCount([out] unsigned long count);
    SetSampleAttributes([in] struct AudioSampleAttributesHAL attrs);
    GetSampleAttributes([out] struct AudioSampleAttributesHAL attrs);
    GetCurrentChannelId([out] unsigned int channelId);
    SetExtraParams([in] String keyValueList);
    GetExtraParams([out] String keyValueList);
    ReqMmapBuffer([in] int reqSize,[out] struct AudioMmapBufferDescripterHAL desc);
    GetMmapPosition([out] unsigned long frames,[out] struct AudioTimeStampHAL time);
}